### ISSUE TITLE
Capitalization in HPPs includes

### ISSUE THREAD

**Issue by Nathn** [HollWelleu/autoCPPFiles#3]
When doing the command `./createCPPFiles ExampleClass`
Line 8 of the created .hpp file is : 
`#ifndef ExampleClass_HPP_`
while it should be : 
`#ifndef EXAMPLECLASS_HPP_`

same on line 9

**Comment by JeremyCMPro** [comment]
Thanks for your report ! It is done ! You can download and replace your old file by the new and use it again :)
